config/routes.rb
ScratchClientPortal::Application.routes.draw do

  # get 'eventvenue/index'
  # get 'eventvenue/show'

root to: 'sessions#new'
  match '/venues', to: 'venues#index', via: [:get, :post]
  match '/events', to: 'events_user#index', via: [:get, :post]
  match '/past_events', to: 'events_user#show', via: [:get, :post]
  match '/past_clientevents', to: 'venues#past_events', via: [:get, :post]
  #eventvenue#show
  match '/venue/events', to: 'venues#show', via: [:get, :post]
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match '/logout', to: 'sessions#destroy', as: 'logout', via: [:get, :post]
  resources :identities
  resources :venues, :has_many => :events
end

app/models/client.rb
class Client < User
    
end

app/models/event.rb
class Event < ActiveRecord::Base
    has_many :events_users, dependent: :destroy
    has_many :users, through: :events_users
    #has_many :events_venues, dependent: :destroy
    belongs_to :venue
    #has_many :venues, through: :events_venues

    has_many :events_talents, class_name: "EventsTalent"
    has_many :talents, through: :events_talents, source: :user
    has_many :events_clients, class_name: "EventsClient"
    has_many :clients, through: :events_clients, source: :user


    #scope :past, ->{where ("date < ?", Date.today)}
    #scope :upcoming, ->{where ("date > ?", Date.yesterday)}

    def djnames
        names = ""
        talents.each do |talent|
            talent.name
            names= names+"#{talent.name}"
        end
    end
end

app/models/events_client.rb
class EventsClient < EventsUser
    
end

app/models/events_talent.rb
class EventsTalent < EventsUser
    
end

app/models/events_user.rb
class EventsUser < ActiveRecord::Base
     
    belongs_to :user
    belongs_to :event
   
end

app/models/events_venue.rb
class EventsVenue < ActiveRecord::Base
    belongs_to :event
    belongs_to :venue


    
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
 has_secure_password
 validates_presence_of :password, :on => :create
 validates_presence_of :email
 validates_uniqueness_of :email

end

app/models/talent.rb
class Talent < User
    
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :events_users, dependent: :destroy
has_many :events, through: :events_users
has_many :venues, through: :events
#has_many :events_venues, through: :events

  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
    has_many :events
    #has_many :events, through: :events_venues
    #has_many :events_venues, dependent: :destroy
    has_many :users, through: :events
    has_many :events_users, through: :events
    
    #finds events specific to current user
    def events_for_user (user_id)
        events_users.includes(:event).where("events_users.user_id=?",user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def require_login
    unless current_user
      redirect_to root_path
    end
  end

end

app/controllers/events_user_controller.rb
class EventsUserController < ApplicationController
    before_filter :require_login
    def index
    #@user = User.find(params[:user_id])
        @user=current_user
        @events = @user.events.where("date > ?", Date.yesterday)
    end
    def show
        @user=current_user
        @pastevents = @user.events.where("date < ?", Date.today)
    end
end

app/controllers/eventvenue_controller.rb
class EventvenueController < ApplicationController
  before_filter :require_login
  def index

  end

  def show
  #? if model to UserEventVenue @user=User.find(params[:user_id]) or current_user.userevent_venues
    @venue = Venue.find(params[:venue_id])
  #Find events for user in venue
    @events = @venue.events_for_user(current_user.id).where("date >= ?", Date.today).order('date desc')
    #Find EventTalent where events is equal to @events
    @events_in_eventtalent= EventsTalent.where(event_id: @events)
    #get user ids from those events
    #@user_id = EventsTalent.where(event_id: @events).pluck(:user_id)
    #@talent_info= User.where(id: @user_id).pluck(:name)
  
        
  end

  def past_events
    @user=current_user
    @pastevents = @user.events.where("date < ?", Date.today)
  end
 
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  def new
    @identity = env['omniauth.identity']
  end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.from_omniauth(env["omniauth.auth"])
        session[:user_id] = user.id
        type = user.type
        if type == "Client"
            redirect_to venues_path
        else
            redirect_to events_path(:user_id => user.id)
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url
    end

    def failure
        redirect_to root_url, alert: "Authentication failed, please try again"
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_filter :require_login
  def index

  end

  def show
    #Show upcoming Events
    #? if model to UserEventVenue @user=User.find(params[:user_id]) or current_user.userevent_venues
    @venue = Venue.find(params[:venue_id])
    #Find events for user in venue
    @events = @venue.events_for_user(current_user.id).where("date >= ?", Date.today).order('date desc')
    #Find EventTalent where events is equal to @events
    @events_in_eventtalent= EventsTalent.where(event_id: @events)
    #get user ids from those events
    #@user_id = EventsTalent.where(event_id: @events).pluck(:user_id)
    #@talent_info= User.where(id: @user_id).pluck(:name)   
  end

  def past_events
    @user=current_user
    @pastevents = @user.events.where("date < ?", Date.today)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_talent_helper.rb
module EventsTalentHelper
end

app/helpers/events_user_helper.rb
module EventsUserHelper
end

app/helpers/eventvenue_helper.rb
module EventvenueHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/events_user/index.html.erb
<div class="white-pink">
<h1>Upcoming Events for <%=current_user.name%> </h1>

<table class="table table-hover">
     <tr>
        <% if @events.size==0 %>

            <em>No Events found</em>

        <% else %>
   
            <td><b><%= "Name" %></b> </td>
            <td><b><%= "Date" %></b></td>
            <td><b><%= "Time" %></b></td>
            <td><b><%= "Location" %></b></td>
       
                <% @events.each do |event| %>
                    <tr>
                        <td><%= event.name%> </td>
                        <td><%= event.date.strftime("%b %d, %Y") %></td>
                        <td><%= event.time.strftime("%I:%Mp") %></td>
                        <td><%= event.venue.address %><%= event.venue.city %><%= event.venue.state %></td>
                        <td></td>
                    </tr>

                <% end %>
        <% end %>
</table>

</div>

app/views/events_user/show.html.erb
<div class="white-pink">
<h1>Past events held for <%=current_user.name%> </h1>
<table class="table table-hover">
    
    <tr>
        <% if @pastevents.size==0 %>

            <em>No Events found</em>

        <% else %>
            
            <td><b><%= "Name" %></b></td>
            <td><b><%= "Date" %></b></td>
            <td><b><%= "Time" %></b></td>
            <td><b><%= "Location" %></b></td>
    </tr>

            <% @pastevents.each do |pe| %> 
            <tr> 

                <td><%= pe.name %> </td> 
                <td><%= pe.date.strftime("%b %d, %Y") %></td> 
                <td><%= pe.time.strftime("%I:%Mp") %></td> 
                <td><%= pe.venue.address %><%= pe.venue.city %><%= pe.venue.state %></td> 
            </tr> 
        <% end %>
             
    <% end %>

</table>
</div>

app/views/identities/new.html.erb
<div class="white-pink">
<h1>Sign up here</h1>

<%= form_tag "/auth/identity/register" do %>
  <% if @identity && @identity.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% @identity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= label_tag :name %><br>
    <%= text_field_tag :name, @identity.try(:name) %>
  </div>
  <div class="field">
    <%= label_tag :email %><br>
    <%= text_field_tag :email, @identity.try(:email) %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= label_tag :password_confirmation %><br>
    <%= password_field_tag :password_confirmation %>
  </div>
  <div class="actions"><%= submit_tag "Register" %></div>
<% end %>
</div>

app/views/venues/index.html.erb
<div class="white-pink">

<h1>Venues </h1>
<table class="table table-hover">

    <% current_user.venues.group(:name).each do |venue| %>
        <tr><td><b><%= "Venue" %></b></td>
            <td><b><%= "Location" %></b></td>
        </tr>
        
        <tr>
        <td><%= link_to venue.name, venue_events_path(:venue_id => venue.id, :user_id =>current_user.id,:user=>params[:user]) %></td>
        <td><%= venue.address %><%= venue.city %><%= venue.state %></td>
        </tr>
    <% end %>

</table>
    <% if current_user.venues.all.size==0 %>
        <em>No Venues found</em>
    <% end %>

</div>

app/views/venues/past_events.html.erb
<div class="white-pink">
<h1>Past events held for <%=current_user.name%> </h1>
<table>
    
    <tr>
        <% if @pastevents.size==0 %>

            <em>No Events found</em>

        <% else %>
       
            
            <td><b><%= "Name" %></b></td>
            <td><b><%= "Date" %></b></td>
            <td><b><%= "Time" %></b></td>
    </tr>

            <% @pastevents.group(:name).each do |e| %> 
            <tr> 

                <td><%= e.name %> </td> 
                <td><%= e.date.strftime("%b %d, %Y") %></td> 
                <td><%= e.time.strftime("%I:%Mp") %></td>  
            </tr> 
        <% end %>
             
    <% end %>

</table>
</div>

app/views/venues/show.html.erb
<div class="white-pink">
<h1>Events held in <%=@venue.name %></h1>

<table>
    <tr>
        <% if @events.size==0 %>
        <em>No Events found</em>
        <%else%>
            <td><b><%= "Name" %></b></td>
            <td><b><%= "Date" %></b></td>
            <td><b><%= "Event Time" %></b></td>
            <td><b><%= "DJ Name" %></b></td>
            <td><b><%= "DJ Start Time" %></b></td>
            <td><b><%= "DJ End Time" %></b></td>
            <td><b><%= "DJ Cell" %></b></td>
    </tr>
        <% @events.group(:name).each do |e| %>
    <tr>
            <td><%= e.event.name %></td> 
            <td><%= e.event.date.strftime("%b %d, %Y") %></td>
            <td><%= e.event.time.strftime("%I:%Mp") %></td>

            <td>       
                <% @events_in_eventtalent.each do |t| %>

                <tr><td></td>
                    <td></td>
                    <td></td>

                    <td><%= link_to t.user.name, t.user.biolink %></td>
                    <td><%= t.start %></td>
                    <td><%= t.end %></td>
                  <td><%= t.user.dj_cellphone %></td>
                </tr>
                <% end %>
            </td>

            <% end %>
        
    </tr> 
        <% end %>
</table>
</div>