config/routes.rb
ScratchClientPortal::Application.routes.draw do

  # get 'eventvenue/index'
  # get 'eventvenue/show'

root to: 'sessions#new'
  match '/venues', to: 'venues#index', via: [:get, :post]
  match '/events', to: 'events_user#index', via: [:get, :post]
  match '/past_events', to: 'events_user#show', via: [:get, :post]
  match '/past_clientevents', to: 'venues#past_events', via: [:get, :post]
  #eventvenue#show
  match '/venue/events', to: 'venues#show', via: [:get, :post]
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match '/logout', to: 'sessions#destroy', as: 'logout', via: [:get, :post]
  resources :identities
  resources :venues, :has_many => :events
end

app/models/client.rb
class Client < User
    
end

app/models/event.rb
class Event < ActiveRecord::Base
    has_many :events_users, dependent: :destroy
    has_many :users, through: :events_users
    #has_many :events_venues, dependent: :destroy
    belongs_to :venue
    #has_many :venues, through: :events_venues

    has_many :events_talents, class_name: "EventsTalent"
    has_many :talents, through: :events_talents, source: :user
    has_many :events_clients, class_name: "EventsClient"
    has_many :clients, through: :events_clients, source: :user


    #scope :past, ->{where ("date < ?", Date.today)}
    #scope :upcoming, ->{where ("date > ?", Date.yesterday)}

    def djnames
        names = ""
        talents.each do |talent|
            talent.name
            names= names+"#{talent.name}"
        end
    end
end

app/models/events_client.rb
class EventsClient < EventsUser
    
end

app/models/events_talent.rb
class EventsTalent < EventsUser
    
end

app/models/events_user.rb
class EventsUser < ActiveRecord::Base
     
    belongs_to :user
    belongs_to :event
   
end

app/models/events_venue.rb
class EventsVenue < ActiveRecord::Base
    belongs_to :event
    belongs_to :venue


    
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
 has_secure_password
 validates_presence_of :password, :on => :create
 validates_presence_of :email
 validates_uniqueness_of :email

end

app/models/talent.rb
class Talent < User
    
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :events_users, dependent: :destroy
has_many :events, through: :events_users
has_many :venues, through: :events
#has_many :events_venues, through: :events

  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
    has_many :events
    #has_many :events, through: :events_venues
    #has_many :events_venues, dependent: :destroy
    has_many :users, through: :events
    has_many :events_users, through: :events
    
    #finds events specific to current user
    def events_for_user (user_id)
        events_users.includes(:event).where("events_users.user_id=?",user_id)
    end
end

app/controllers/eventvenue_controller.rb
class EventvenueController < ApplicationController
  before_filter :require_login
  def index

  end

  def show
  #? if model to UserEventVenue @user=User.find(params[:user_id]) or current_user.userevent_venues
    @venue = Venue.find(params[:venue_id])
  #Find events for user in venue
    @events = @venue.events_for_user(current_user.id).where("date >= ?", Date.today).order('date desc')
    #Find EventTalent where events is equal to @events
    @events_in_eventtalent= EventsTalent.where(event_id: @events)
    #get user ids from those events
    #@user_id = EventsTalent.where(event_id: @events).pluck(:user_id)
    #@talent_info= User.where(id: @user_id).pluck(:name)
  
        
  end

  def past_events
    @user=current_user
    @pastevents = @user.events.where("date < ?", Date.today)
  end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.from_omniauth(env["omniauth.auth"])
        session[:user_id] = user.id
        type = user.type
        if type == "Client"
            redirect_to venues_path
        else
            redirect_to events_path(:user_id => user.id)
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url
    end

    def failure
        redirect_to root_url, alert: "Authentication failed, please try again"
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_filter :require_login
  def index

  end

  def show
    #Show upcoming Events
    #? if model to UserEventVenue @user=User.find(params[:user_id]) or current_user.userevent_venues
    @venue = Venue.find(params[:venue_id])
    #Find events for user in venue
    @events = @venue.events_for_user(current_user.id).where("date >= ?", Date.today).order('date desc')
    #Find EventTalent where events is equal to @events
    @events_in_eventtalent= EventsTalent.where(event_id: @events)
    #get user ids from those events
    #@user_id = EventsTalent.where(event_id: @events).pluck(:user_id)
    #@talent_info= User.where(id: @user_id).pluck(:name)   
  end

  def past_events
    @user=current_user
    @pastevents = @user.events.where("date < ?", Date.today)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_talent_helper.rb
module EventsTalentHelper
end

app/helpers/events_user_helper.rb
module EventsUserHelper
end

app/helpers/eventvenue_helper.rb
module EventvenueHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<a href="http://railstutorial.org/">Rails Tutorial</a>
by Michael Hartl
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<header class="navbar navbar-fixed-top navbar-inverse">

	<div class="navbar-inner">
		<div class="container">
<% if current_user %>
  <!-- #converts type to a symbol, more optimal then checking string -->

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Scratch Client Portal</a>
    <ul class="nav">
      <li class="active">
      

      <% if current_user.type.downcase.to_sym == :client %>

              <% if params[:controller] == 'venues' && params[:action] == 'show' %>
                <li><%= link_to "Past Events", past_clientevents_path%></li>
                <li><%= link_to "Log out", logout_path %></li>

              <%elsif params[:controller] =='venues'&& params[:action] == 'index'%>

                <li><%= link_to "Log out", logout_path %></li>

              <% else %>
              <li><%= link_to "Upcoming Events", venues_path%></li>
                <li><%= link_to "Log out", logout_path %></li>

              <% end %>

      <%elsif current_user.type.downcase.to_sym == :talent %>

              <% if current_page?(controller: 'events_user', action: 'show') %>
                 <li><%= link_to "Upcoming Events", events_path%></li>
                 <li> <%= link_to "Log out", logout_path %></li>
              <%elsif current_page?(controller: 'events_user', action: 'index')%>
                <li><%= link_to "Past Events", past_events_path%></li>
                <li><%= link_to "Log out", logout_path %></li>
              <% end %>

      <% else %>
                
              <%= link_to "Sign in", root_path %>
            
              <% end %>
      <% end %>

    </ul>
  </div>
</div>
			
		</div>
  </div>
</header>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Client Portal</title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div id="container">
    
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    
    <%= yield %>
  
    </div>
  </body>

</html>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

	<div class="navbar-inner">
		<div class="container">

			<% if current_user %>
				<p><%= link_to "Log out", logout_path %></p>
			<% else %>
                <%= link_to "Sign in", root_path %>
            
            <% end %>
            
		</div>
    </div>
</header>